# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-23 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsuse',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
