---
image: docker:19.03.11-git
services:
  - docker:19.03.11-dind
stages:
  - build
  - deploy

variables:
  DJANGO_RELEASE_IMAGE: $CI_REGISTRY_IMAGE/django:$CI_BUILD_REF_NAME
  DJANGO_HOMOLOG_IMAGE: $CI_REGISTRY_IMAGE/django:$CI_BUILD_REF_NAME-$CI_COMMIT_SHORT_SHA
  KUBECONFIG: /etc/k8s-config

##########
## Homolog
##########
build to homolog:
  stage: build
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build --build-arg DJANGO_AWS_ACCESS_KEY_ID=${DJANGO_AWS_ACCESS_KEY_ID_DEV} --build-arg DJANGO_AWS_SECRET_ACCESS_KEY=${DJANGO_AWS_SECRET_ACCESS_KEY_DEV} --build-arg DJANGO_AWS_STORAGE_BUCKET_NAME=${DJANGO_AWS_STORAGE_BUCKET_NAME_DEV} -f compose/production/Dockerfile -t $DJANGO_HOMOLOG_IMAGE .
    - docker push $DJANGO_HOMOLOG_IMAGE
  only:
    - /feature-docker-support/
  environment: homolog
  tags:
    - docker

deploy to homolog:
  stage: deploy
  image: hacklab/kubectl:latest
  script:
    - echo ${kube_config} | base64 -d > ${KUBECONFIG}
    - kubectl -n masteraula-dev --record deployment.apps/masteraula-back set image deployment.v1.apps/masteraula-back masteraula-back=$DJANGO_HOMOLOG_IMAGE
  only:
    - /feature\/docker-support/
  environment: homolog
  variables:
    GIT_STRATEGY: none
  tags:
    - docker

#############
## Production
#############
build to production:
  stage: build
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build -f compose/production/Dockerfile -t $DJANGO_RELEASE_IMAGE .
    - docker tag $DJANGO_RELEASE_IMAGE "$CI_REGISTRY_IMAGE/django:latest"
    - docker push $DJANGO_RELEASE_IMAGE
    - docker push "$CI_REGISTRY_IMAGE/django:latest"
  only:
    - tags
  environment: production
  tags:
    - docker

# deploy to production:
#   stage: deploy
#   image: hacklab/kubectl:latest
#   script:
#     - echo ${kube_config} | base64 -d > ${KUBECONFIG}
#     - kubectl -n <project-name>-prod --record deployment.apps/django set image deployment.v1.apps/django django=$DJANGO_RELEASE_IMAGE nginx=$NGINX_RELEASE_IMAGE
#   only:
#     - tags
#   environment: production
#   variables:
#     GIT_STRATEGY: none
#   tags:
#     - docker
