# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-10 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_header',
            field=models.TextField(),
        ),
    ]
