# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-15 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20170310_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='question_statement',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_header',
        ),
    ]
