# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-07-12 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_auto_20180710_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='teaching_level',
        ),
        migrations.AddField(
            model_name='question',
            name='teaching_levels',
            field=models.ManyToManyField(blank=True, null=True, to='questions.TeachingLevel'),
        ),
    ]
