# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-07-12 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_auto_20180712_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='desciptors',
            new_name='descriptors',
        ),
    ]
