# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-08-06 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0020_auto_20180718_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentheader',
            name='owner',
        ),
        migrations.AlterField(
            model_name='documentheader',
            name='class_indicator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documentheader',
            name='date_indicator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documentheader',
            name='discipline_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='documentheader',
            name='institution_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='documentheader',
            name='professor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='documentheader',
            name='score_indicator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documentheader',
            name='student_indicator',
            field=models.BooleanField(default=False),
        ),
    ]
