# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-08-06 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_auto_20180806_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.DocumentHeader'),
        ),
    ]
