# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-08-06 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0024_auto_20180806_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_header',
        ),
        migrations.AddField(
            model_name='document',
            name='class_indicator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='date_indicator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='discipline_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='institution_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='professor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='score_indicator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='student_indicator',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='DocumentHeader',
        ),
    ]
