# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-26 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0025_auto_20180806_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
