# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-30 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0026_auto_20181026_1111'),
        ('questions', '0027_auto_20181025_1536'),
    ]

    operations = [
    ]
