# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-11-22 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0028_merge_20181030_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningobject',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
    ]
