# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-11-27 18:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0028_merge_20181030_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('institution_name', models.CharField(blank=True, max_length=200, null=True)),
                ('discipline_name', models.CharField(blank=True, max_length=50, null=True)),
                ('professor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('student_indicator', models.BooleanField(default=False)),
                ('class_indicator', models.BooleanField(default=False)),
                ('score_indicator', models.BooleanField(default=False)),
                ('date_indicator', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
