# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-11-28 14:32
from __future__ import unicode_literals

from django.db import migrations, models

questions_objects = {}

def migrate_data_before(apps, schema_editor):
    Question = apps.get_model('questions', 'Question')
    for question in Question.objects.filter(learning_object__isnull=False):
        questions_objects[question.id] = question.learning_object.id

def migrate_data_after(apps, schema_editor):
    LearningObject = apps.get_model('questions', 'LearningObject')
    Question = apps.get_model('questions', 'Question')
    for question_id in questions_objects:
        question = Question.objects.get(id=question_id)
        learning_object = LearningObject.objects.get(id=questions_objects[question_id])
        question.learning_objects.add(learning_object)
        question.save()

class Migration(migrations.Migration):
    dependencies = [
        ('questions', '0029_learningobject_source'),
    ]
    operations = [
        migrations.RunPython(migrate_data_before, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='question',
            name='learning_object',
        ),
        migrations.AddField(
            model_name='question',
            name='learning_objects',
            field=models.ManyToManyField(blank=True, to='questions.LearningObject'),
        ),
        migrations.RunPython(migrate_data_after, reverse_code=migrations.RunPython.noop)
    ]