# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-11-28 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0030_auto_20181128_1232'),
        ('questions', '0030_auto_20181127_1621'),
    ]

    operations = [
    ]
