# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-05 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0032_source_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='slug',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teachinglevel',
            name='slug',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
