# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-12 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0034_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='questions.Topic'),
        ),
    ]
