# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-12 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0035_auto_20190212_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topics',
            field=models.ManyToManyField(blank=True, to='questions.Topic'),
        ),
    ]
