# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-26 17:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0038_auto_20190218_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100)),
                ('difficulty', models.CharField(blank=True, max_length=20, null=True)),
                ('source', models.CharField(blank=True, max_length=150, null=True)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('date_search', models.DateTimeField(auto_now_add=True)),
                ('disciplines', models.ManyToManyField(blank=True, to='questions.Discipline')),
                ('teaching_levels', models.ManyToManyField(blank=True, to='questions.TeachingLevel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search',
                'verbose_name_plural': 'Searches',
            },
        ),      
    ]
