# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-18 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0039_auto_20190225_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('', 'None'), ('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], max_length=1, null=True),
        ),
    ]
