# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-19 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0041_documentdownload'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdownload',
            name='answers',
            field=models.BooleanField(default=False),
        ),
    ]
