# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-06 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0043_question_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningobject',
            name='type_object',
            field=models.TextField(blank=True, null=True),
        ),
    ]
