# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-17 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0045_auto_20190816_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='learning_objects',
            field=models.ManyToManyField(blank=True, related_name='questions', to='questions.LearningObject'),
        ),
    ]
