# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-11 15:22
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
from django.db.models import Q
import django.db.models.deletion

def migrate_learning_object_type(apps, schema_editor):
    LearningObject = apps.get_model('questions', 'LearningObject')

    learning_objects_images = []
    learning_objects_texts = []

    print(len(LearningObject.objects.all()))
    for learning_object in LearningObject.objects.all():
        if bool(learning_object.image):
            learning_objects_images.append(learning_object.id)
        if learning_object.text:
            learning_objects_texts.append(learning_object.id)

    LearningObject.objects.filter(Q(id__in=learning_objects_images) & Q(id__in=learning_objects_texts)).update(object_types=['I', 'T'])
    LearningObject.objects.filter(object_types=[]).filter(id__in=learning_objects_texts).update(object_types=['T'])
    LearningObject.objects.filter(object_types=[]).filter(id__in=learning_objects_images).update(object_types=['I'])

class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0047_documentpublication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningobject',
            name='type_object',
        ),
        migrations.AddField(
            model_name='learningobject',
            name='object_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('I', 'Image'), ('T', 'Text'), ('A', 'Audio'), ('V', 'Video')], max_length=1), default=[], size=None),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_learning_object_type, reverse_code=migrations.RunPython.noop),
    ]
