# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-15 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0048_auto_20191014_0856'),
        ('questions', '0048_auto_20191011_1222'),
    ]

    operations = [
    ]
