# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-16 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0049_merge_20191015_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='term',
            field=models.TextField(),
        ),
    ]
