# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-05 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0050_auto_20191016_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100)),
                ('topics', models.ManyToManyField(to='questions.Topic')),
            ],
        ),
        migrations.AlterModelOptions(
            name='documentdownload',
            options={'ordering': ['id']},
        ),
    ]
