# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-09 14:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0051_auto_20191105_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, choices=[('', 'None'), ('#FFFF33', 'Yellow'), ('#A849F7', 'Purple'), ('#F9442E', 'Red'), ('#BABEBF', 'Grey'), ('#050505', 'Black'), ('#FC1979', 'Pink'), ('#FC7320', 'Orange'), ('#9AEE2E', 'Light Green'), ('#569505', 'Dark Green'), ('#82C2FB', 'Light Blue'), ('#055195', 'Dark Blue')], max_length=7, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='labels',
            field=models.ManyToManyField(blank=True, to='questions.Label'),
        ),
    ]
