# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-16 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0052_auto_20191204_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Label')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='labels',
        ),
        migrations.AddField(
            model_name='questionlabel',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question'),
        ),
    ]
