# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-16 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0053_auto_20191216_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='labels',
            field=models.ManyToManyField(related_name='labels', through='questions.QuestionLabel', to='questions.Label'),
        ),
    ]
