# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-10 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0054_auto_20200130_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classplan',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='discipline',
            options={'ordering': ['-name']},
        ),
        migrations.RemoveField(
            model_name='classplan',
            name='links',
        ),
        migrations.AddField(
            model_name='link',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='questions.ClassPlan'),
        ),
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.TextField(max_length=2083),
        ),
    ]
