# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-09 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0055_auto_20200210_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='classplan',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
