# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-17 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0056_classplan_disabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_station', models.TextField()),
                ('document', models.ManyToManyField(blank=True, related_name='station_doc', to='questions.Document')),
                ('learning_object', models.ManyToManyField(blank=True, related_name='station_obj', to='questions.LearningObject')),
            ],
        ),
        migrations.AddField(
            model_name='classplan',
            name='plan_types',
            field=models.CharField(blank=True, choices=[('T', 'Traditional'), ('S', 'Station')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='questions.ClassPlan'),
        ),
        migrations.AddField(
            model_name='station',
            name='question',
            field=models.ManyToManyField(blank=True, related_name='station_question', to='questions.Question'),
        ),
    ]
