# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-01 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0057_auto_20200319_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description_category', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Faq Category',
                'verbose_name_plural': 'FAQ categories',
            },
        ),
        migrations.CreateModel(
            name='FaqQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_question', models.TextField()),
                ('faq_answer', models.TextField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_questions', to='questions.FaqCategory')),
            ],
        ),
    ]
