# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-23 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0059_auto_20200422_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentanswer',
            old_name='answer',
            new_name='answer_text',
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='answer_alternative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Alternative'),
        ),
    ]
