# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-27 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0060_auto_20200423_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentquestiononline',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='total_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='score_answer',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
