# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-27 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0060_auto_20200423_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentquestiononline',
            options={'ordering': ['order'], 'verbose_name': 'Document Question Online', 'verbose_name_plural': 'Document Question Online'},
        ),
        migrations.AddField(
            model_name='documentquestiononline',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentquestiononline',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='total_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='score_answer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
