# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-27 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0061_auto_20200427_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentquestiononline',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='total_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='score_answer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
