# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-08 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0061_auto_20200427_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentanswer',
            options={'ordering': ['student_question']},
        ),
        migrations.RemoveField(
            model_name='result',
            name='total_score',
        ),
    ]
