# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-27 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0062_auto_20200427_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentquestiononline',
            options={'ordering': ['order'], 'verbose_name': 'Document Question Online', 'verbose_name_plural': 'Document Question Online'},
        ),
        migrations.AddField(
            model_name='documentquestiononline',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
