# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-24 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0065_learningobject_disabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bncc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Bncc',
                'verbose_name_plural': 'BNCC',
            },
        ),
    ]
