# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-31 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0067_auto_20200727_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareclassplan',
            name='user',
        ),
        migrations.AlterField(
            model_name='shareclassplan',
            name='class_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_class_plan', to='questions.ClassPlanPublication'),
        ),
    ]
