# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-13 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0069_auto_20200804_2044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classplanpublication',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shareclassplan',
            options={'ordering': ['link']},
        ),
        migrations.AlterField(
            model_name='documentonline',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_document_online', to='questions.Document'),
        ),
    ]
