# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-13 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0070_auto_20200813_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='classplanpublication',
            name='secret',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='secret',
            field=models.BooleanField(default=False),
        ),
    ]
