# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-13 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0071_auto_20200813_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentonline',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
