# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-09-19 14:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180718_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('uf', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('uf_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Name should contain only valid characters', regex='^[A-Za-zÀ-ÿ ]+$')]),
        ),
        migrations.AddField(
            model_name='city',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.State'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.City'),
        ),
    ]
