# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-24 14:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180919_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Name should contain only valid characters', regex="^[A-Za-zÀ-ÿ-´' ]+$")]),
        ),
    ]
