# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-01-24 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import masteraula.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profile_pics', validators=[masteraula.users.models.User.validate_image]),
        ),
    ]
