# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-21 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0042_documentdownload_answers'),
        ('users', '0009_auto_20190124_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disciplines',
            field=models.ManyToManyField(related_name='users_discipline', to='questions.Discipline'),
        ),
    ]
