# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-16 19:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import masteraula.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190911_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField(default=masteraula.users.models.next_month)),
                ('note', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
