# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-17 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20170316_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='year_level',
            field=models.CharField(blank=True, choices=[('Ensino Médio', 'Ensino Médio'), ('Fundamental II - anos finais', 'Fundamental II - anos finais'), ('Fundamental II - anos iniciais', 'Fundamental II - anos iniciais'), ('Ensino Superior', 'Ensino Superior')], max_length=30, null=True),
        ),
    ]
