# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20161005_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='question_list',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='question_list',
            name='question_list_header',
            field=models.CharField(max_length=200, verbose_name='Nome da Lista'),
        ),
    ]
