# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-17 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question_year_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
