# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20161018_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_list',
            name='private',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
