# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-11 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20170322_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question_list',
            old_name='private',
            new_name='secret',
        ),
    ]
