# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_question_list_cloned_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_list',
            name='private',
            field=models.BooleanField(verbose_name='Lista privada'),
        ),
    ]
