# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20161021_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_list',
            name='cloned_from',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subarticles', to='questions.Question_List'),
        ),
    ]
