# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 13:41
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_auto_20161028_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
