# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_auto_20161107_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionquestion_list',
            options={'ordering': ['order']},
        ),
    ]
