# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_auto_20161107_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterField(
            model_name='questionquestion_list',
            name='order',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
