# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_auto_20161107_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(blank=True, choices=[('', 'Nenhuma opção'), ('E', 'Fácil'), ('M', 'Médio'), ('H', 'Difícil')], max_length=1, null=True),
        ),
    ]
