# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-23 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_auto_20161222_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_list',
            name='cloned_from',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Question_List'),
        ),
        migrations.AlterField(
            model_name='question_list',
            name='questions',
            field=models.ManyToManyField(related_name='question_set', through='questions.QuestionQuestion_List', to='questions.Question'),
        ),
    ]
