# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-04 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_auto_20161223_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_list',
            name='questions',
            field=models.ManyToManyField(related_name='questions', through='questions.QuestionQuestion_List', to='questions.Question'),
        ),
    ]
