# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-04 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0022_auto_20170104_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_list',
            name='questions',
            field=models.ManyToManyField(through='questions.QuestionQuestion_List', to='questions.Question'),
        ),
        migrations.AlterField(
            model_name='questionquestion_list',
            name='order',
            field=models.PositiveIntegerField(),
        ),
    ]
