# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-05 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0023_auto_20170104_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avaiable_questions',
            field=models.ManyToManyField(to='questions.Question'),
        ),
        migrations.AlterField(
            model_name='question_list',
            name='questions',
            field=models.ManyToManyField(related_name='questions', through='questions.QuestionQuestion_List', to='questions.Question'),
        ),
    ]
