# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-06 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0024_auto_20170105_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avaiable_questions',
            field=models.ManyToManyField(blank=True, to='questions.Question'),
        ),
    ]
